services:
    node:
        image: node:latest
        container_name: my-node-dev
        volumes:
            - .:/workspaces
        working_dir: /workspaces
        command: sleep infinity
        ports:
            - "3000:3000" # React
            - "4200:4200" # Angular
            - "5173:5173" # Vite
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:latest
        container_name: my-mongo-dev
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:latest
        container_name: my-redis-dev
        ports:
            - "6379:6379"

volumes:
    mongo-data:
